	AREA RESET,DATA,READONLY
	EXPORT __Vectors
__Vectors
	DCD 0X10001000
	DCD Reset_Handler
	ALIGN
	AREA mycode,CODE,READONLY
	ENTRY
	EXPORT Reset_Handler
Reset_Handler
	LDR R0,=VAL1
	LDR R1,=VAL2
	LDR R2,=DST
	LDR R3,[R0]
	LDR R4,[R1]
	LDR R5,=0X0
BACK ADD R5,R3
	SUBS R4,#1
	BNE BACK
	STR R5,[R2]
VAL1 DCD 0X3
VAL2 DCD 0X4
	AREA mydata,DATA,READWRITE
DST DCD 0
	END
