	AREA RESET,CODE,READONLY
	EXPORT __Vectors
__Vectors
	DCD 0X10001000
	DCD Reset_Handler
	ALIGN
	AREA mycode,CODE,READONLY
	ENTRY
	EXPORT Reset_Handler
Reset_Handler
	MOV R2,#1			;R2 IS ACTING AS i
	LDR R0,=NO1
	LDR R1,=NO2
	LDR R6,=DST
	LDR R3,[R0]
	LDR R4,[R1]
BACK MUL R5,R2,R3
MOD CMP R5,R4			;FINDING THE REMAINDER USING REPETITIVE SUBTRACTION
	BLO UP1		;WHEN R5<R1 
	SUB R5,R4
	B MOD
UP1
	CMP R5,#0
	BEQ EXIT1
	ADD R2,#1			;INCREMENTING THE VALUE OF i
	B BACK
EXIT1 MUL R5,R2,R3
	STR R5,[R6]
NO1 DCD 0X3
NO2 DCD 0X2
	AREA mydata,DATA,READWRITE
DST DCD 0
	END
